/*
 * Copyright (C) 2016 Tim Guenther
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package de.guenther.tim.burp.gui;

import burp.IBurpExtenderCallbacks;
import de.guenther.tim.burp.utils.Logging;

/**
 *
 * @author Tim Guenther
 */
public class UIPanel extends javax.swing.JPanel {
    
    public static boolean interceptEnabled = false;
    
    public static boolean infoEnabled = true;
    public static boolean debugEnabled = true;
    public static boolean errorEnabled = true;
    
    public static boolean spiderEnabled = true;
    public static boolean scannerEnabled = true;
    public static boolean intruderEnabled = true;
    public static boolean repeaterEnabled = true;

    /**
     * Creates new form UIPanel
     */
    public UIPanel() {
        initComponents();
    }
    
    public UIPanel(IBurpExtenderCallbacks callbacks){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HelpTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OptionsPanel = new javax.swing.JPanel();
        ToolsPanel = new javax.swing.JPanel();
        SpiderCheckBox = new javax.swing.JCheckBox();
        ScannerCheckBox = new javax.swing.JCheckBox();
        IntruderCheckBox = new javax.swing.JCheckBox();
        RepeaterCheckBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DebugPanel = new javax.swing.JPanel();
        LoggingPanel = new javax.swing.JPanel();
        InfoCheckBox = new javax.swing.JCheckBox();
        DebugCheckBox = new javax.swing.JCheckBox();
        ErrorCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        InterceptToggleButton = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel4 = new javax.swing.JPanel();

        ToolsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tools"));

        SpiderCheckBox.setSelected(true);
        SpiderCheckBox.setText("Spider");
        SpiderCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpiderCheckBoxActionPerformed(evt);
            }
        });

        ScannerCheckBox.setSelected(true);
        ScannerCheckBox.setText("Scanner");
        ScannerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScannerCheckBoxActionPerformed(evt);
            }
        });

        IntruderCheckBox.setSelected(true);
        IntruderCheckBox.setText("Intruder");
        IntruderCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntruderCheckBoxActionPerformed(evt);
            }
        });

        RepeaterCheckBox.setSelected(true);
        RepeaterCheckBox.setText("Repeater");
        RepeaterCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeaterCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToolsPanelLayout = new javax.swing.GroupLayout(ToolsPanel);
        ToolsPanel.setLayout(ToolsPanelLayout);
        ToolsPanelLayout.setHorizontalGroup(
            ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SpiderCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScannerCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IntruderCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepeaterCheckBox)
                .addGap(0, 180, Short.MAX_VALUE))
        );
        ToolsPanelLayout.setVerticalGroup(
            ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(SpiderCheckBox)
                .addComponent(ScannerCheckBox)
                .addComponent(IntruderCheckBox)
                .addComponent(RepeaterCheckBox))
        );

        javax.swing.GroupLayout OptionsPanelLayout = new javax.swing.GroupLayout(OptionsPanel);
        OptionsPanel.setLayout(OptionsPanelLayout);
        OptionsPanelLayout.setHorizontalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OptionsPanelLayout.setVerticalGroup(
            OptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsPanelLayout.createSequentialGroup()
                .addComponent(ToolsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 330, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(OptionsPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        HelpTabbedPane.addTab("Options", jPanel1);

        LoggingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Logging"));

        InfoCheckBox.setSelected(true);
        InfoCheckBox.setText("Info");
        InfoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoCheckBoxActionPerformed(evt);
            }
        });

        DebugCheckBox.setSelected(true);
        DebugCheckBox.setText("Debug");
        DebugCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebugCheckBoxActionPerformed(evt);
            }
        });

        ErrorCheckBox.setSelected(true);
        ErrorCheckBox.setText("Error");
        ErrorCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoggingPanelLayout = new javax.swing.GroupLayout(LoggingPanel);
        LoggingPanel.setLayout(LoggingPanelLayout);
        LoggingPanelLayout.setHorizontalGroup(
            LoggingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoggingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DebugCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorCheckBox)
                .addGap(0, 325, Short.MAX_VALUE))
        );
        LoggingPanelLayout.setVerticalGroup(
            LoggingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoggingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(InfoCheckBox)
                .addComponent(DebugCheckBox)
                .addComponent(ErrorCheckBox))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Debugging Output"));

        InterceptToggleButton.setText("Intercept");
        InterceptToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterceptToggleButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(InterceptToggleButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(InterceptToggleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DebugPanelLayout = new javax.swing.GroupLayout(DebugPanel);
        DebugPanel.setLayout(DebugPanelLayout);
        DebugPanelLayout.setHorizontalGroup(
            DebugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoggingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DebugPanelLayout.setVerticalGroup(
            DebugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DebugPanelLayout.createSequentialGroup()
                .addComponent(LoggingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(DebugPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        HelpTabbedPane.addTab("Debug", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        HelpTabbedPane.addTab("Help", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HelpTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HelpTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        HelpTabbedPane.getAccessibleContext().setAccessibleName("Options");
    }// </editor-fold>//GEN-END:initComponents

    private void InterceptToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterceptToggleButtonActionPerformed
        interceptEnabled = !interceptEnabled;
        Logging.getInstance().log(getClass(), "Intercept = "+interceptEnabled, Logging.INFO);
    }//GEN-LAST:event_InterceptToggleButtonActionPerformed

    private void InfoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoCheckBoxActionPerformed
        infoEnabled = !infoEnabled;
    }//GEN-LAST:event_InfoCheckBoxActionPerformed

    private void DebugCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebugCheckBoxActionPerformed
        debugEnabled = !debugEnabled;
    }//GEN-LAST:event_DebugCheckBoxActionPerformed

    private void ErrorCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorCheckBoxActionPerformed
        errorEnabled = !errorEnabled;
    }//GEN-LAST:event_ErrorCheckBoxActionPerformed

    private void SpiderCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpiderCheckBoxActionPerformed
        spiderEnabled = !spiderEnabled;
    }//GEN-LAST:event_SpiderCheckBoxActionPerformed

    private void ScannerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScannerCheckBoxActionPerformed
        scannerEnabled = !scannerEnabled;
    }//GEN-LAST:event_ScannerCheckBoxActionPerformed

    private void IntruderCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntruderCheckBoxActionPerformed
        intruderEnabled = ! intruderEnabled;
    }//GEN-LAST:event_IntruderCheckBoxActionPerformed

    private void RepeaterCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeaterCheckBoxActionPerformed
        repeaterEnabled = ! repeaterEnabled;
    }//GEN-LAST:event_RepeaterCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DebugCheckBox;
    private javax.swing.JPanel DebugPanel;
    private javax.swing.JCheckBox ErrorCheckBox;
    private javax.swing.JTabbedPane HelpTabbedPane;
    private javax.swing.JCheckBox InfoCheckBox;
    private javax.swing.JToggleButton InterceptToggleButton;
    private javax.swing.JCheckBox IntruderCheckBox;
    private javax.swing.JPanel LoggingPanel;
    private javax.swing.JPanel OptionsPanel;
    private javax.swing.JCheckBox RepeaterCheckBox;
    private javax.swing.JCheckBox ScannerCheckBox;
    private javax.swing.JCheckBox SpiderCheckBox;
    private javax.swing.JPanel ToolsPanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
